In [1]:
from __future__ import print_function
from pprint import *
import numpy as np

Basic Stuff
================

In [61]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [62]:
a.dtype

dtype('int64')

In [31]:
a.astype(np.float64)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [26]:
a.shape  ##particularly useful as a no nonsense check 

(100000000,)

In [4]:
a.reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [32]:
a.reshape((10,)) ##both astype and reshape are not inplace operations

ValueError: total size of new array must be unchanged

In [63]:
a.reshape((-1,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

Aliasing
----------

In [6]:
b = a
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b[0][1] = 10
b

array([[ 1, 10,  3],
       [ 4,  5,  6]])

In [8]:
a

array([[ 1, 10,  3],
       [ 4,  5,  6]])

Pass by reference
------------------

In [12]:
def func(a):
    a[0,1] = 10
a = np.zeros((3,3))
func(a)
a

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 25.3 µs


Efficeint
----------

In [18]:
a = np.arange(100000000)

In [23]:
%%time
sum = 0
for x in a:
    sum+=x
print(sum)

4999999950000000
CPU times: user 21.6 s, sys: 0 ns, total: 21.6 s
Wall time: 21.6 s


In [24]:
%%time
np.sum(a)

CPU times: user 120 ms, sys: 0 ns, total: 120 ms
Wall time: 117 ms


4999999950000000

Array level operations
--------------------------

In [47]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a2*a1

array([ 4, 10, 18])

In [36]:
c = np.linspace(0,9,10) ##unlike most functions in python, the endpoint is included here
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [37]:
np.exp(c)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [38]:
c_rs = c.reshape((2,5))
np.log(c_rs)

/home/deepak_saini/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: divide by zero encountered in log
  from ipykernel import kernelapp as app


array([[       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436],
       [ 1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458]])

Printing np array
-------------------

In [45]:
a = np.arange(1024).reshape((32,32))
a

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
          11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
          22,   23,   24,   25,   26,   27,   28,   29,   30,   31],
       [  32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
          43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
          54,   55,   56,   57,   58,   59,   60,   61,   62,   63],
       [  64,   65,   66,   67,   68,   69,   70,   71,   72,   73,   74,
          75,   76,   77,   78,   79,   80,   81,   82,   83,   84,   85,
          86,   87,   88,   89,   90,   91,   92,   93,   94,   95],
       [  96,   97,   98,   99,  100,  101,  102,  103,  104,  105,  106,
         107,  108,  109,  110,  111,  112,  113,  114,  115,  116,  117,
         118,  119,  120,  121,  122,  123,  124,  125,  126,  127],
       [ 128,  129,  130,  131,  132,  133,  134,  135,  136,  137,  138,
         139,  140,  141,  142,  143,  144,  145,  146,  1

In [44]:
np.set_printoptions(threshold=np.nan)

Axes
-------

In [49]:
a = np.arange(20).reshape((4,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [50]:
np.sum(a,axis=0)

array([30, 34, 38, 42, 46])

In [51]:
np.mean(a,axis=1)

array([  2.,   7.,  12.,  17.])

Upcasting
------------

In [53]:
a = np.array([1,2,3,4],dtype=np.float64)
b = np.array([1,2,3,4])
print(a)
print(b)

[ 1.  2.  3.  4.]
[1 2 3 4]


In [56]:
c = a+b
c.dtype

dtype('float64')

In [58]:
a+=b ##Inplace operation
a

array([  3.,   6.,   9.,  12.])

In [59]:
b+=a ##Data types is fundamental property of an array, you can't modify that

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

Slicing
---------

In [77]:
def f(i,j):
    return 2*i+3*j
a = np.fromfunction(f,(5,10))
a

array([[  0.,   3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.],
       [  2.,   5.,   8.,  11.,  14.,  17.,  20.,  23.,  26.,  29.],
       [  4.,   7.,  10.,  13.,  16.,  19.,  22.,  25.,  28.,  31.],
       [  6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.,  30.,  33.],
       [  8.,  11.,  14.,  17.,  20.,  23.,  26.,  29.,  32.,  35.]])

In [68]:
print(a[1,2])
print(a[1][2])

12
12


In [70]:
a[0,1:4] ##remember the end point is not incldedd

array([1, 2, 3])

In [76]:
a[1:3,2:6]

array([[12, 13, 14, 15],
       [22, 23, 24, 25]])

In [78]:
a[:,0:10:2]

array([[  0.,   6.,  12.,  18.,  24.],
       [  2.,   8.,  14.,  20.,  26.],
       [  4.,  10.,  16.,  22.,  28.],
       [  6.,  12.,  18.,  24.,  30.],
       [  8.,  14.,  20.,  26.,  32.]])

In [82]:
a[-2,-1]

33.0

In [81]:
a[: :-1]

array([[  8.,  11.,  14.,  17.,  20.,  23.,  26.,  29.,  32.,  35.],
       [  6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.,  30.,  33.],
       [  4.,   7.,  10.,  13.,  16.,  19.,  22.,  25.,  28.,  31.],
       [  2.,   5.,   8.,  11.,  14.,  17.,  20.,  23.,  26.,  29.],
       [  0.,   3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.]])

In [87]:
list(a.flat) ##returns an iterator

[0.0,
 3.0,
 6.0,
 9.0,
 12.0,
 15.0,
 18.0,
 21.0,
 24.0,
 27.0,
 2.0,
 5.0,
 8.0,
 11.0,
 14.0,
 17.0,
 20.0,
 23.0,
 26.0,
 29.0,
 4.0,
 7.0,
 10.0,
 13.0,
 16.0,
 19.0,
 22.0,
 25.0,
 28.0,
 31.0,
 6.0,
 9.0,
 12.0,
 15.0,
 18.0,
 21.0,
 24.0,
 27.0,
 30.0,
 33.0,
 8.0,
 11.0,
 14.0,
 17.0,
 20.0,
 23.0,
 26.0,
 29.0,
 32.0,
 35.0]

In [88]:
a

array([[  0.,   3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.],
       [  2.,   5.,   8.,  11.,  14.,  17.,  20.,  23.,  26.,  29.],
       [  4.,   7.,  10.,  13.,  16.,  19.,  22.,  25.,  28.,  31.],
       [  6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.,  30.,  33.],
       [  8.,  11.,  14.,  17.,  20.,  23.,  26.,  29.,  32.,  35.]])

In [101]:
i = np.array([[0,1],[2,3]])
a[i]

array([[[  0.,   3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.],
        [  2.,   5.,   8.,  11.,  14.,  17.,  20.,  23.,  26.,  29.]],

       [[  4.,   7.,  10.,  13.,  16.,  19.,  22.,  25.,  28.,  31.],
        [  6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.,  30.,  33.]]])

In [102]:
j = np.array([[0,0],[1,1]])
a[i,j]

array([[ 0.,  2.],
       [ 7.,  9.]])

In [104]:
a[1,j]

array([[ 2.,  2.],
       [ 5.,  5.]])

In [105]:
b = np.copy(a)
b[i,j] = 0
b

array([[  0.,   3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.],
       [  0.,   5.,   8.,  11.,  14.,  17.,  20.,  23.,  26.,  29.],
       [  4.,   0.,  10.,  13.,  16.,  19.,  22.,  25.,  28.,  31.],
       [  6.,   0.,  12.,  15.,  18.,  21.,  24.,  27.,  30.,  33.],
       [  8.,  11.,  14.,  17.,  20.,  23.,  26.,  29.,  32.,  35.]])

In [96]:
#fun way to transpose an array
x = np.array([[i for i in range(5)]])
i = np.repeat(x,10,axis=0)
i

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [98]:
y = np.arange(10).reshape((10,-1))
j = np.repeat(y,5,axis=1)
j

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9]])

In [99]:
a[i,j]

array([[  0.,   2.,   4.,   6.,   8.],
       [  3.,   5.,   7.,   9.,  11.],
       [  6.,   8.,  10.,  12.,  14.],
       [  9.,  11.,  13.,  15.,  17.],
       [ 12.,  14.,  16.,  18.,  20.],
       [ 15.,  17.,  19.,  21.,  23.],
       [ 18.,  20.,  22.,  24.,  26.],
       [ 21.,  23.,  25.,  27.,  29.],
       [ 24.,  26.,  28.,  30.,  32.],
       [ 27.,  29.,  31.,  33.,  35.]])

In [106]:
##Boolean indexing
print(a)

[[  0.   3.   6.   9.  12.  15.  18.  21.  24.  27.]
 [  2.   5.   8.  11.  14.  17.  20.  23.  26.  29.]
 [  4.   7.  10.  13.  16.  19.  22.  25.  28.  31.]
 [  6.   9.  12.  15.  18.  21.  24.  27.  30.  33.]
 [  8.  11.  14.  17.  20.  23.  26.  29.  32.  35.]]


In [108]:
b = a>10
b

array([[False, False, False, False,  True,  True,  True,  True,  True,
         True],
       [False, False, False,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False,  True,  True,  True,  True,  True,  True,
         True],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [109]:
a[b]

array([ 12.,  15.,  18.,  21.,  24.,  27.,  11.,  14.,  17.,  20.,  23.,
        26.,  29.,  13.,  16.,  19.,  22.,  25.,  28.,  31.,  12.,  15.,
        18.,  21.,  24.,  27.,  30.,  33.,  11.,  14.,  17.,  20.,  23.,
        26.,  29.,  32.,  35.])

In [111]:
c = a.copy()
c[b] = -1
c

array([[  0.,   3.,   6.,   9.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.],
       [  2.,   5.,   8.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.],
       [  4.,   7.,  10.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.],
       [  6.,   9.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.],
       [  8.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.,  -1.]])

Stacking
-----------

In [115]:
x = np.arange(0,10,2)                     
y = np.arange(5)                          
print(x)
print(y)

[0 2 4 6 8]
[0 1 2 3 4]


In [117]:
a = np.vstack([x,y])
a

array([[0, 2, 4, 6, 8],
       [0, 1, 2, 3, 4]])

In [118]:
b = np.hstack([x,y]) 
b

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

More Relevant Stuff
=====================

np arrays as matrices
-----------------------

In [112]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[6,7]])

In [113]:
a.T

array([[1, 3],
       [2, 4]])

In [114]:
np.dot(a,b) #matrix mult

array([[16, 19],
       [36, 43]])

Linear algebra ops : numpy linalg
-----------------------------------

In [120]:
a = np.arange(25).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [121]:
i5 = np.eye(5)

In [123]:
np.all(a.dot(i5)==a)

True

In [124]:
np.trace(a)

60

In [125]:
np.linalg.inv(a)

LinAlgError: Singular matrix

In [126]:
np.linalg.matrix_rank(a)

2

In [127]:
np.linalg.eig(a)

(array([  6.39116499e+01,  -3.91164992e+00,  -4.06523933e-15,
          2.58443073e-16,   1.51528038e-15]),
 array([[-0.0851802 ,  0.67779864, -0.46549901,  0.18772213, -0.00207481],
        [-0.23825372,  0.36348873,  0.55597991, -0.0514454 , -0.41636356],
        [-0.39132723,  0.04917881, -0.15590518, -0.65194893,  0.2955311 ],
        [-0.54440074, -0.2651311 ,  0.50586667,  0.70734553,  0.66632773],
        [-0.69747425, -0.57944101, -0.44044239, -0.19167334, -0.54342046]]))